name: bendfm
channels:
  - conda-forge
  - dglteam/label/th24_cu121
  - defaults

dependencies:
  - python=3.9
  - numpy
  - scipy
  - networkx
  - scikit-learn==1.0.2
  - tqdm
  - dgl
  - pip

  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - lightning>=2.0
      - open3d
      - termcolor==1.1.0
      - multimethod==1.7
      - shortuuid
      - h5py==3.6.0
      - plyfile
      - tensorboard
      - pyyaml==6.0
      - easydict==1.9
